version: "3.9"

services:
  app:
    build: .
    container_name: fastapi-todo
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - OTEL_ENABLED=true
    depends_on:
      - otel-collector

  otel-collector:
    image: otel/opentelemetry-collector-contrib:latest
    container_name: otel-collector
    volumes:
      - ./otel-collector-config.yaml:/etc/otelcol/config.yaml
    command: ["--config", "/etc/otelcol/config.yaml"]
    ports:
      - "4318:4318"  # HTTP OTLP
